//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infonet.CStoreCommander.WebApi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infonet.CStoreCommander.WebApi.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to authToken.
        /// </summary>
        internal static string AuthToken {
            get {
                return ResourceManager.GetString("AuthToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card is required.
        /// </summary>
        internal static string CardRequired {
            get {
                return ResourceManager.GetString("CardRequired", resourceCulture);
            }
        }


        internal static string ConnectionFailed
        {
            get
            {
                return ResourceManager.GetString("Connection failed with Loyalty server", resourceCulture);
            }


        }

        /// <summary>
        ///   Looks up a localized string similar to Code is required.
        /// </summary>
        internal static string CodeRequired {
            get {
                return ResourceManager.GetString("CodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no customers defined.
        /// </summary>
        internal static string CustomerNotDefined {
            get {
                return ResourceManager.GetString("CustomerNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer does not exists.
        /// </summary>
        internal static string CustomerNotExists {
            get {
                return ResourceManager.GetString("CustomerNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error Occurred! Please check api logs for more info..
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Upload a file upto 1 mb..
        /// </summary>
        internal static string ImageSizeMessage {
            get {
                return ResourceManager.GetString("ImageSizeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Auth token..
        /// </summary>
        internal static string InvalidAuthToken {
            get {
                return ResourceManager.GetString("InvalidAuthToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data entered.
        /// </summary>
        internal static string InvalidDataEntered {
            get {
                return ResourceManager.GetString("InvalidDataEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Information.
        /// </summary>
        internal static string InvalidInformation {
            get {
                return ResourceManager.GetString("InvalidInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request is Invalid.
        /// </summary>
        internal static string InvalidRequest {
            get {
                return ResourceManager.GetString("InvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Stock Code..
        /// </summary>
        internal static string InvalidStockCode {
            get {
                return ResourceManager.GetString("InvalidStockCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to line is required..
        /// </summary>
        internal static string LineRequired {
            get {
                return ResourceManager.GetString("LineRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDP Port is already Opened.
        /// </summary>
        internal static string PortAlreadyOpenMessage {
            get {
                return ResourceManager.GetString("PortAlreadyOpenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Does not Exist.
        /// </summary>
        internal static string SaleNotExist {
            get {
                return ResourceManager.GetString("SaleNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock does not exists.
        /// </summary>
        internal static string StockNotExists {
            get {
                return ResourceManager.GetString("StockNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Till does not exists.
        /// </summary>
        internal static string TillNotExist {
            get {
                return ResourceManager.GetString("TillNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Upload a image..
        /// </summary>
        internal static string UploadImageError {
            get {
                return ResourceManager.GetString("UploadImageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Upload image of type .jpg,.bmp,.png..
        /// </summary>
        internal static string UploadImageMessage {
            get {
                return ResourceManager.GetString("UploadImageMessage", resourceCulture);
            }


        }

        internal static string PointsNull
        {
            get
            {
                return ResourceManager.GetString("Null Points", resourceCulture);
            }
        }
    }
}
